ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN echo "Test of our custom dockerfile"

RUN bash -c 'echo \"current directory: $PWD\"'
RUN bash -c 'rosdep update && rosdep install --from-paths /workspaces/isaac_ros-dev/src/ --ignore-src -r -y'
